version: 2
jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Install required dependencies
          command: apt update && apt install -y git cmake
      - run:
          name: Install compiler
          command: apt install -y clang lcov
      - run:
          name: Fetch submodules
          command: git submodule update --init --recursive
      - run:
          name: Generate build stuff
          command: mkdir build; cd build; cmake -DBUILD_TESTS=On -DBUILD_COVERAGE=On ..
      - run:
          name: Make
          command: cd build && make -j4
      - run:
          name: Test
          command: cd build && make test
