ARG FEDORA_VERSION="41"

FROM fedora:${FEDORA_VERSION}
WORKDIR /src

ARG BUILD_TYPE="system"
ENV BUILD_TYPE=${BUILD_TYPE}

RUN dnf update --assumeyes && \
        dnf install --assumeyes cmake g++ ninja git

ADD . /src

CMD ["./scripts/run-test.sh"]
